### ISSUE TITLE
Holidays not detected when providing time

### ISSUE THREAD

**Issue by NicoHaase** [umulmrum/holiday#3]
On Oct 3 2019, I detected a small problem using your wonderful holiday detector: to avoid problems with the timezone, my code uses the following statement for checking for a holiday:

```
$today = new \DateTimeImmutable('today 13:00:00');
$holidayCalculator = new HolidayCalculator(new GermanyHolidayInitializer());
$holidayHelper     = new HolidayHelper($holidayCalculator);
$isAHoliday = $holidayHelper->isDayAHoliday($today, NorthRhineWestphalia::ID);
```

This does not return true, as the filtering process checks for a starting time of 00:00:00. I must admit that I haven't found a proper way to fix that bug in your code, that's why I haven't directly submitted a PR. But I would love to hear your opinion about this - do I use your code wrong or is this really a bug?

**Comment by umulmrum** [comment]
Hi @NicoHaase, 

first of all: I'm very sorry for not answering for such a long time, 2019 and 2020 have been really intense and I didn't find the time for open source maintenance.

In case you still use the lib: Before the break I prepared a major redesign that is close to getting finished. This will simplify usage by a great deal, and your use case can then be written as such (and will work :-) ):

```php
$calculator = new HolidayCalculator();
$holidayList = $calculator->calculateHolidaysForYear(NorthRhineWestphalia::class, 2019);
$isAHoliday =$holidayList->isHoliday(new \DateTime('2019-10-03'));
```

If you're interested, have a look at the master branch where the changes are already merged (CHANGELOG.md already contains a coarse overview over the changes, but upgrading instructions are not there yet). This is still in the making though, because I'd like to avoid other major API changes before 1.0.0, so don't use master in production.

**Comment by umulmrum** [comment]
Closing, as the problem should no longer occur.
